baseURL = "https://vericert.ymhg.org"
languageCode = "en-uk"
title = "Vericert"
copyright = "Â© 2020-2021 Yann Herklotz"
theme = "book"
enableGitInfo = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]

[[menu.after]]
  name = "Github mirror"
  url = "https://github.com/ymherklotz/vericert"
  weight = 10

[[menu.after]]
  name = "Git repository"
  url = "https://sr.ht/~ymherklotz/vericert"
  weight = 20

[params]
  BookTheme = "auto"
  BookSection = "/"
  BookRepo = "https://github.com/ymherklotz/vericert"
  BookSearch = true

[permalinks]
  blog = '/:year/:month/:title/'
